project/app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('', home, name='home'),
    path('words', WordListView.as_view(), name='words'),
    path('words/upload', words_upload_form, name='words_upload'),
    path('cards', CardListView.as_view(), name='cards'),
    path('cards/upload', cards_upload_form, name='cards_upload'),
]

project/project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/app/models.py
from django.db import models


class Card(models.Model):
    ru_word = models.CharField(max_length=30)
    en_word = models.CharField(max_length=30)
    pic = models.ImageField(upload_to='images/')


class Word(models.Model):
    ru_word = models.CharField(max_length=30)
    en_word = models.CharField(max_length=30)

project/app/forms.py
from django import forms
from .models import Card, Word


class CardForm(forms.ModelForm):
    ru_word = forms.CharField(label='На русском')
    en_word = forms.CharField(label='На английском')
    pic = forms.ImageField(label='Картинка')

    class Meta:
        model = Card
        fields = ['ru_word', 'en_word', 'pic']


class WordForm(forms.ModelForm):
    ru_word = forms.CharField(label='На русском')
    en_word = forms.CharField(label='На английском')

    class Meta:
        model = Word
        fields = ['ru_word', 'en_word']

project/app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Card, Word
from .forms import CardForm, WordForm


def home(request):
    return render(request, "index.html")


class CardListView(ListView):
    model = Card
    template_name = 'cards.html'


class WordListView(ListView):
    model = Word
    template_name = 'words.html'


def cards_upload_form(request):
    if request.method == 'POST':
        form = CardForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect('app:cards')
    else:
        form = CardForm()
    return render(request, 'cards-upload.html', {'form': form})


def words_upload_form(request):
    if request.method == 'POST':
        form = WordForm(data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('app:words')
    else:
        form = WordForm()
    return render(request, 'words-upload.html', {'form': form})

project/app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>{% block pagetitle %}{% endblock %}</title>
        <!-- load static -->
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
        <!-- CSS -->
        <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
        {% block extra_head %}{% endblock %}
    </head>
    <body>
        <main>
            <header class="border-bottom py-3">
                <div class="container d-flex justify-content-center align-items-center gap-5">
                    <a href="/words" class="text-dark text-decoration-none"> Слова </a>
                    <a href="/" class="d-flex justify-content-center align-items-center
                        bg-dark text-dark text-decoration-none py-2 px-4 rounded-3"
                    >
                        <div style="font-size: 28px; font-weight: bold; color: #FFFFFF;"> Learn English </div>
                    </a>
                    <a href="/cards" class="text-dark text-decoration-none"> Карточки </a>
                </div>
            </header>
            <div class="container pt-4">
                <div class="p-5 mb-4 bg-light rounded-3" id="title-box">
                    <div class="container-fluid py-5">
                        <h1 class="display-1 fw-bold">{% block page-title %}{% endblock %}</h1>
                        <p class="fs-4">{% block page-lead %}{% endblock %}</p>
                    </div>
                </div>
                {% block content %}{% endblock %}
            </div>
            <footer class="footer pt-3 mt-4 text-muted border-top py-3">
                <div class="container d-flex justify-content-center">
                    Петр Грачев © 2023
                </div>
            </footer>
        </main>
    </body>
</html>

project/app/templates/cards-upload.html
{% extends "base.html" %}

{% block page-title %}
Загрузка карточки
{% endblock %}

{% block page-lead %}
На данной странице вы можете загрузить карточку для запоминания слов
{% endblock %}

{% block content %}
<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="w-25" type="submit">Загрузить</button>
</form>
{% endblock %}

project/app/templates/cards.html
{% extends "base.html" %}

{% block extra_head %}
<link href="static/cards.css" rel="stylesheet">
{% endblock %}

{% block pagetitle %}
Карточки слов
{% endblock %}

{% block page-title %}
Карточки слов
{% endblock %}

{% block page-lead %}
На данной странице вы можете посмотреть ваши карточки слов. Вы можете загрузить карточку <a href="{% url 'app:cards_upload' %}">здесь</a>
Анки-карточки могут быть использованы для изучения новых тем, повторения материала, а также для подготовки к экзаменам и тестированию.
Этот метод обучения популярен среди студентов и профессионалов, которые хотят эффективно запомнить большое количество информации.
{% endblock %}

{% block content %}
<div class="d-flex flex-wrap justify-content-between align-items-center gap-4">
{% for card in object_list %}
    <div class="card">
        <div class="card_word">{{ card.en_word }}</div>
        <div class="card_img-wrapper">
            <img class="card_img" src="{{ card.pic.url }}"/>
        </div>
        <div class="card_word card_ru-word">{{ card.ru_word }}</div>
    </div>
{% endfor %}
</div>
{% endblock %}

project/app/templates/index.html
{% extends "base.html" %}

{% block page-title %}
Изучение языков
{% endblock %}

{% block page-lead %}
Это страничка проекта про изучение иностранных языков. <br/>
Анки-карточки - это метод обучения, основанный на использовании электронных карточек с вопросами и ответами.
Этот метод был разработан японским программистом и бывшим медицинским студентом Дайсукэ Мураками в 2006 году.
{% endblock %}

{% block content %}
<div class="container px-4 py-5" id="project-contents">
    <h2 class="pb-2 border-bottom">Что есть в этом проекте</h2>
    <div class="d-flex px-xl-5 justify-content-around">
        <div class="w-25 d-flex">
            <div class="bg-secondary p-3 rounded-2 d-flex flex-column justify-content-between align-items-center">
                <div>
                    <h3 class="fs-2">Список слов</h3>
                    <p>Здесь вы можете посмотреть какие слова вы уже изучили. А также изучать новые слова.</p>
                </div>
                <a href="/words" class="btn btn-primary">Посмотреть</a>
            </div>
        </div>
        <div class="w-25 d-flex">
            <div class="bg-secondary p-3 rounded-2 d-flex flex-column justify-content-between align-items-center">
                <div>
                    <h3 class="fs-2">Посмотреть карточки</h3>
                    <p>Здесь вы можете посмотреть сколько карточек уже у вас есть. А также добавить новые карточки.</p>
                </div>
                <a href="/cards" class="btn btn-primary">
                        Посмотреть
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/app/templates/words-upload.html
{% extends "base.html" %}

{% block page-title %}
Загрузка слов
{% endblock %}

{% block page-lead %}
На данной странице вы можете загрузить слова
{% endblock %}

{% block content %}
<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="w-25" type="submit">Загрузить</button>
</form>
{% endblock %}

project/app/templates/words.html
{% extends "base.html" %}

{% block extra_head %}
<link href="static/words.css" rel="stylesheet">
{% endblock %}

{% block pagetitle %}
Иностранные слова
{% endblock %}

{% block page-title %}
Иностранные слова
{% endblock %}

{% block page-lead %}
На данной странице вы можете посмотреть ваши слова.
Изучайте новые слова, а также не забывайте регулярно повторять уже пройденный материал.
Вы можете загрузить слово <a href="{% url 'app:words_upload' %}">здесь.</a>
{% endblock %}

{% block content %}
<div class="d-flex flex-wrap justify-content-start align-items-center gap-5">
{% for word in object_list %}
    <div class="bg-secondary p-2 rounded-3" style="min-width: 140px;">
        <h4 class="text-light font-weight-bold">{{ word.en_word }}</h4>
        <div>{{ word.ru_word }}</div>
    </div>
{% endfor %}
</div>
{% endblock %}